# Generated by Django 5.0.4 on 2024-04-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_majorcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorcategory',
            options={'verbose_name_plural': 'Major Sub Categories'},
        ),
    ]
