# Generated by Django 5.0.4 on 2024-05-01 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_experttips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experttips',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
