# Generated by Django 5.0.4 on 2024-04-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_experttips_delete_tips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertTips',
        ),
    ]
